### ISSUE TITLE
ps2exe.azurewebsites.net Flagged as virus/malware

### ISSUE THREAD

**Issue by thmmsn** [rzander/PS2EXE#3]
Hi. Couldn't find any issues reported here on GH, but several on reddit...

Tested your web app today and Defender for Business reported the exported .exe as malware. A scan on https://virustotal.com detected malicious code.

The following link contains a simple script containing only the command `Copy-Item`
https://www.virustotal.com/gui/file/e1cd98fe2ef47cd1f8bf0e396eef2cbe6b7de8234d9a89573c200952bc208232/detection

https://www.reddit.com/r/PowerShell/comments/s2h6f1/powershell_script_converted_to_scriptexe_anti/

**Comment by rzander** [comment]
An unsigned executable that runs Base64 encoded powershell code is suspicious... Nothing to add.  Try to sign the executable and check if its still reported...

**Comment by connor33341** [comment]
More probable than not, this is a trojan, it drops files and checks language settings. Has that baked in Russian malware

**Comment by rzander** [comment]
The tool is OpenSource, you can check the code and compile your own instance if you do not trust the published instance...
